public class Datatles {
    public static void main(String[] args) {

        System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA DATA TYPES");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("As explained in the previous chapter, a variable in Java must be a specified data type:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int myNum = 5;               // Integer (whole number)");
        System.out.println("float myFloatNum = 5.99f;    // Floating point number");
        System.out.println("char myLetter = 'D';         // Character");
        System.out.println("boolean myBool = true;       // Boolean");
        System.out.println("String myText = \"Hello\";     // String");
        System.out.println("");
        System.out.println("");
        System.out.println("Data types are divided into two groups:");
        System.out.println("");
        System.out.println("Primitive data types - includes byte, short, int, long, float, double, boolean and char");
        System.out.println("Non-primitive data types - such as String, Arrays and Classes (you will learn more about these in a later chapter)");
        System.out.println("");
        System.out.println("");
        System.out.println("Primitive Data Types");
        System.out.println("");
        System.out.println("A primitive data type specifies the type of a variable and the kind of values it can hold.");
        System.out.println("");
        System.out.println("There are eight primitive data types in Java:");
        System.out.println("");
        System.out.println("Data Type\tDescription");
        System.out.println("byte\tStores whole numbers from -128 to 127");
        System.out.println("short\tStores whole numbers from -32,768 to 32,767");
        System.out.println("int\tStores whole numbers from -2,147,483,648 to 2,147,483,647");
        System.out.println("long\tStores whole numbers from -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807");
        System.out.println("float\tStores fractional numbers. Sufficient for storing 6 to 7 decimal digits");
        System.out.println("double\tStores fractional numbers. Sufficient for storing 15 to 16 decimal digits");
        System.out.println("boolean\tStores true or false values");
        System.out.println("char\tStores a single character/letter or ASCII values");
        System.out.println("");
        System.out.println("");
        System.out.println("You Cannot Change the Type");
        System.out.println("");
        System.out.println("Once a variable is declared with a type, it cannot change to another type later in the program:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int myNum = 5;       // myNum is an int");
        System.out.println("// myNum = \"Hello\";  // Error: cannot assign a String to an int");
        System.out.println("");
        System.out.println("String myText = \"Hi\"; // myText is a String");
        System.out.println("// myText = 123;      // Error: cannot assign a number to a String");
        System.out.println("");
        System.out.println("");
        System.out.println("Note: This rule makes Java safer, because the compiler will stop you if you try to mix up types by mistake.");
        System.out.println("");
        System.out.println("If you really need to change between types,");
        System.out.println(" you must use type casting or conversion methods (for example, turning an int into a double).");
        System.out.println("");
        System.out.println("");
         System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA NUMBERS");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("Numbers");
        System.out.println("");
        System.out.println("Primitive number types are divided into two groups:");
        System.out.println("");
        System.out.println("Integer types stores whole numbers, positive or negative (such as 123 or -456), ");
        System.out.println("without decimals. Valid types are byte, short, int and long. Which type you should use, depends on the numeric value.");
        System.out.println("");
        System.out.println("Floating point types represents numbers with a fractional part,");
        System.out.println("containing one or more decimals. There are two types: float and double.");
        System.out.println("");
        System.out.println("");
        System.out.println("Even though there are many numeric types in Java, ");
        System.out.println("the most used for numbers are int (for whole numbers) and double (for floating point numbers). ");
        System.out.println("However, we will describe them all as you continue to read.");
        System.out.println("");
        System.out.println("");
        System.out.println("Integer Types");
        System.out.println("");
        System.out.println("Byte");
        System.out.println("");
        System.out.println("The byte data type can store whole numbers from -128 to 127. ");
        System.out.println("This can be used instead of int or other integer types to save memory when ");
        System.out.println("you are certain that the value will be within -128 and 127:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("byte myNum = 100;");
        System.out.println("System.out.println(myNum);");
        System.out.println("");
        System.out.println("");
        System.out.println("Short");
        System.out.println("");
        System.out.println("The short data type can store whole numbers from -32768 to 32767:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("short myNum = 5000;");
        System.out.println("System.out.println(myNum);");
        System.out.println("");
        System.out.println("");
        System.out.println("Int");
        System.out.println("");
        System.out.println("The int data type can store whole numbers from -2147483648 to 2147483647. In general, ");
        System.out.println("and in our tutorial, the int data type is the preferred data type when we create variables with a numeric value.");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int myNum = 100000;");
        System.out.println("System.out.println(myNum);");
        System.out.println("");
        System.out.println("");
        System.out.println("Long");
        System.out.println("");
        System.out.println("The long data type can store whole numbers from -9223372036854775808 to 9223372036854775807.");
        System.out.println("This is used when int is not large enough to store the value. Note that you should end the value with an \"L\":");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("long myNum = 15000000000L;");
        System.out.println("System.out.println(myNum);");
        System.out.println("");
        System.out.println("");
        System.out.println("Floating Point Types");
        System.out.println("");
        System.out.println("You should use a floating point type whenever you need a number with a decimal, such as 9.99 or 3.14515.");
        System.out.println("");
        System.out.println("The float and double data types can store fractional numbers.");
        System.out.println("Note that you should end the value with an \"f\" for floats and \"d\" for doubles:");
        System.out.println("");
        System.out.println("");
        System.out.println("Float Example");
        System.out.println("");
        System.out.println("float myNum = 5.75f;");
        System.out.println("System.out.println(myNum);");
        System.out.println("");
        System.out.println("");
        System.out.println("Double Example");
        System.out.println("");
        System.out.println("double myNum = 19.99d;");
        System.out.println("System.out.println(myNum);");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("Use float or double?");
        System.out.println("");
        System.out.println("The precision of a floating point value indicates how many digits the value can have after the decimal point.");
        System.out.println("The precision of float is only 6-7 decimal digits,");
        System.out.println("while double variables have a precision of about 16 digits.");
        System.out.println("");
        System.out.println("Therefore it is safer to use double for most calculations.");
        System.out.println("");
        System.out.println("");
        System.out.println("Scientific Numbers");
        System.out.println("");
        System.out.println("A floating point number can also be a scientific number with an \"e\" to indicate the power of 10:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("float f1 = 35e3f;");
        System.out.println("double d1 = 12E4d;");
        System.out.println("System.out.println(f1);");
        System.out.println("System.out.println(d1);");
        System.out.println("");
        System.out.println("");
        System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA BOOLEANS");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("Very often in programming, you will need a data type that can only have one of two values, like:");
        System.out.println("");
        System.out.println("YES / NO");
        System.out.println("ON / OFF");
        System.out.println("TRUE / FALSE");
        System.out.println("");
        System.out.println("For this, Java has a boolean data type, which can only take the values true or false:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("boolean isJavaFun = true;");
        System.out.println("boolean isFishTasty = false;");
        System.out.println("System.out.println(isJavaFun);     // Outputs true");
        System.out.println("System.out.println(isFishTasty);   // Outputs false");
         System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA CHARACTERS");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("The char data type is used to store a single character. The character must be surrounded by single quotes, like 'A' or 'c':");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("char myGrade = 'B';");
        System.out.println("System.out.println(myGrade);");
        System.out.println("");
        System.out.println("");
        System.out.println("Alternatively, if you are familiar with ASCII values, you can use those to display certain characters:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("char myVar1 = 65, myVar2 = 66, myVar3 = 67;");
        System.out.println("System.out.println(myVar1); ");
        System.out.println("System.out.println(myVar2);");
        System.out.println("System.out.println(myVar3);");
        System.out.println("");
        System.out.println("");
        System.out.println("Strings");
        System.out.println("");
        System.out.println("The String data type is used to store a sequence of characters (text). String values must be surrounded by double quotes:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("String greeting = \"Hello World\";");
        System.out.println("System.out.println(greeting);");
        System.out.println("");
        System.out.println("");
        System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA DATA TYPES EXAMPLE");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("Here's a real-life example of using different data types, to calculate and output the total cost of a number of items:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("// Create variables of different data types");
        System.out.println("int items = 50;");
        System.out.println("float costPerItem = 9.99f;  ");
        System.out.println("float totalCost = items * costPerItem;");
        System.out.println("char currency = '$';");
        System.out.println("");
        System.out.println("// Print variables");
        System.out.println("System.out.println(\"Number of items: \" + items);");
        System.out.println("System.out.println(\"Cost per item: \" + costPerItem + currency);");
        System.out.println("System.out.println(\"Total cost = \" + totalCost + currency);");
        System.out.println("");
        System.out.println("");
         System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA NON PRIMATIVE DATA TYPES");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("Non-primitive data types are called reference types because they refer to objects.");
        System.out.println("");
        System.out.println("The main differences between primitive and non-primitive data types are:");
        System.out.println("");
        System.out.println("Primitive types in Java are predefined and built into the language, ");
        System.out.println("while non-primitive types are created by the programmer (except for String).");
        System.out.println("");
        System.out.println("Non-primitive types can be used to call methods to perform certain operations, whereas primitive types cannot.");
        System.out.println("");
        System.out.println("Primitive types start with a lowercase letter (like int), ");
        System.out.println("while non-primitive types typically starts with an uppercase letter (like String).");
        System.out.println("");
        System.out.println("Primitive types always hold a value, whereas non-primitive types can be null.");
        System.out.println("");
        System.out.println("");
          System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA var");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("The var Keyword");
        System.out.println("");
        System.out.println("The var keyword was introduced in Java 10 (released in 2018).");
        System.out.println("The var keyword lets the compiler automatically detect the type of a variable based on the value you assign to it.");
        System.out.println("");
        System.out.println("This helps you write cleaner code and avoid repeating types, especially for long or complex types.");
        System.out.println("");
        System.out.println("For example, instead of writing int x = 5;, you can write:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("var x = 5;  // x is an int");
        System.out.println("System.out.println(x);");
        System.out.println("");
        System.out.println("");
        System.out.println("When using var, the compiler understands that 5 is an int.");
        System.out.println("");
        System.out.println("Example with Different Types");
        System.out.println("");
        System.out.println("");
        System.out.println("Here are some examples showing how var can be used to create variables of different types, based on the values you assign:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("var myNum = 5;         // int");
        System.out.println("var myDouble = 9.98;   // double");
        System.out.println("var myChar = 'D';      // char");
        System.out.println("var myBoolean = true;  // boolean");
        System.out.println("var myString = \"Hello\"; // String");
        System.out.println("");
        System.out.println("");
        System.out.println("Important Notes");
        System.out.println("");
        System.out.println("1. var only works when you assign a value at the same time (you can't declare var x; without assigning a value):");
        System.out.println("");
        System.out.println("var x; // Error");
        System.out.println("var x = 5;  // OK");
        System.out.println("");
        System.out.println("2. Once the type is chosen, it stays the same. See example below:");
        System.out.println("");
        System.out.println("var x = 5;  // x is now an int");
        System.out.println("x = 10;     // OK - still an int");
        System.out.println("x = 9.99;   // Error - can't assign a double to an int");
        System.out.println("");
        System.out.println("");
        System.out.println("When to Use var");
        System.out.println("");
        System.out.println("For simple variables, it's usually clearer to write the type directly (int, double, char, etc.).");
        System.out.println("");
        System.out.println("But for more complex types, such as ArrayList or HashMap, var can make the code shorter and easier to read:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("// Without var");
        System.out.println("ArrayList<String> cars = new ArrayList<String>();");
        System.out.println("");
        System.out.println("// With var");
        System.out.println("var cars = new ArrayList<String>();");
        System.out.println("");
        System.out.println("");
       
        
    }
    
}
