public class Stringles {
    public static void main(String[] args) {




         System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA STRING");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("Strings are used for storing text.");
        System.out.println("");
        System.out.println("A String variable contains a collection of characters surrounded by double quotes (\"\"):");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("Create a variable of type String and assign it a value:");
        System.out.println("");
        System.out.println("String greeting = \"Hello\";");
        System.out.println("");
        System.out.println("");
        System.out.println("String Length");
        System.out.println("");
        System.out.println("A String in Java is actually an object, which means it contains methods that can perform certain operations on strings.");
        System.out.println("");
        System.out.println("For example, you can find the length of a string with the length() method:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("String txt = \"ABCDEFGHIJKLMNOPQRSTUVWXYZ\";");
        System.out.println("System.out.println(\"The length of the txt string is: \" + txt.length());");
        System.out.println("");
        System.out.println("");
        System.out.println("More String Methods");
        System.out.println("");
        System.out.println("There are many string methods available in Java.");
        System.out.println("");
        System.out.println("For example:");
        System.out.println("");
        System.out.println("The toUpperCase() method converts a string to upper case letters.");
        System.out.println("The toLowerCase() method converts a string to lower case letters.");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("String txt = \"Hello World\";");
        System.out.println("System.out.println(txt.toUpperCase());   // Outputs \"HELLO WORLD\"");
        System.out.println("System.out.println(txt.toLowerCase());   // Outputs \"hello world\"");
        System.out.println("");
        System.out.println("");
        System.out.println("Finding a Character in a StringThe indexOf() method returns the index ");
        System.out.println("(the position) of the first occurrence of a specified text in a string (including whitespace):");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("String txt = \"Please locate where 'locate' occurs!\";");
        System.out.println("System.out.println(txt.indexOf(\"locate\")); // Outputs 7");
        System.out.println("");
        System.out.println("");
        System.out.println("Java counts positions from zero.");
        System.out.println("0 is the first position in a string, 1 is the second, 2 is the third ...");
        System.out.println("");
        System.out.println("");
        System.out.println("You can use the charAt() method to access a character at a specific position in a string:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("String txt = \"Hello\";");
        System.out.println("System.out.println(txt.charAt(0));  // H");
        System.out.println("System.out.println(txt.charAt(4));  // o");
        System.out.println("");
        System.out.println("Comparing Strings");
        System.out.println("");
        System.out.println("To compare two strings, you can use the equals() method:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("String txt1 = \"Hello\";");
        System.out.println("String txt2 = \"Hello\";");
        System.out.println("");
        System.out.println("String txt3 = \"Greetings\";");
        System.out.println("String txt4 = \"Great things\";");
        System.out.println("");
        System.out.println("System.out.println(txt1.equals(txt2));  // true");
        System.out.println("System.out.println(txt3.equals(txt4));  // false");
        System.out.println("");
        System.out.println("");
        System.out.println("Removing Whitespace");
        System.out.println("");
        System.out.println("The trim() method removes whitespace from the beginning and the end of a string:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("String txt = \"   Hello World   \";");
        System.out.println("System.out.println(\"Before: [\" + txt + \"]\");");
        System.out.println("System.out.println(\"After:  [\" + txt.trim() + \"]\");");
        System.out.println("");
        System.out.println("Result:");
        System.out.println("");
        System.out.println("Before: [   Hello World   ]");
        System.out.println("After: [Hello World]");
          System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA CONCATENATION");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("String Concatenation");
        System.out.println("");
        System.out.println("The + operator can be used between strings to combine them. This is called concatenation:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("String firstName = \"John\";");
        System.out.println("String lastName = \"Doe\";");
        System.out.println("");
        System.out.println("System.out.println(firstName + \" \" + lastName);");
        System.out.println("");
        System.out.println("");
        System.out.println("Note that we have added an empty text (\" \") to create a space between firstName and lastName on print.");
        System.out.println("");
        System.out.println("");
        System.out.println("Concatenation in Sentences");
        System.out.println("");
        System.out.println("You can use string concatenation to build sentences with both text and variables:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("String name = \"John\";");
        System.out.println("int age = 25;");
        System.out.println("System.out.println(\"My name is \" + name + \" and I am \" + age + \" years old.\");");
        System.out.println("");
        System.out.println("Result:");
        System.out.println("");
        System.out.println("My name is John and I am 25 years old.");
        System.out.println("");
        System.out.println("");
        System.out.println("The concat() Method");
        System.out.println("");
        System.out.println("You can also use the concat() method to concatenate strings:");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("String firstName = \"John \";");
        System.out.println("String lastName = \"Doe\";");
        System.out.println("System.out.println(firstName.concat(lastName));");
        System.out.println("");
        System.out.println("");
        System.out.println("You can also join more than two strings by chaining concat() calls:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("String a = \"Java \";");
        System.out.println("String b = \"is \";");
        System.out.println("String c = \"fun!\";");
        System.out.println("String result = a.concat(b).concat(c);");
        System.out.println("System.out.println(result);");
        System.out.println("");
        System.out.println("");
        System.out.println("Note: While you can use concat() to join multiple strings, ");
        System.out.println("most developers prefer the + operator because it is shorter and easier to read");
        System.out.println("");
        System.out.println("");
        System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA NUMBER & STRING");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("Adding Numbers and Strings");
        System.out.println("");
        System.out.println("");
        System.out.println("WARNING!");
        System.out.println("");
        System.out.println("Java uses the + operator for both addition and concatenation.");
        System.out.println("Numbers are added. Strings are concatenated.");
        System.out.println("");
        System.out.println("");
        System.out.println("If you add two numbers, the result will be a number:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int x = 10;");
        System.out.println("int y = 20;");
        System.out.println("int z = x + y;  // z will be 30 (an integer/number)");
        System.out.println("");
        System.out.println("");
        System.out.println("If you add two strings, the result will be a string concatenation:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("String x = \"10\";");
        System.out.println("String y = \"20\";");
        System.out.println("");
        System.out.println("String z = x + y;  // z will be 1020 (a String)");
        System.out.println("");
        System.out.println("");
        System.out.println("If you add a number and a string, the result will be a string concatenation:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("String x = \"10\";");
        System.out.println("int y = 20;");
        System.out.println("String z = x + y;  // z will be 1020 (a String)");
        System.out.println("");
        System.out.println("");
        System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA SPECIAL CHARACTERS");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("Strings - Special Characters");
        System.out.println("");
        System.out.println("Because strings must be written within quotes, Java will misunderstand this string, and generate an error:");
        System.out.println("");
        System.out.println("");
        System.out.println("String txt = \"We are the so-called \"Vikings\" from the north.\";");
        System.out.println("");
        System.out.println("");
        System.out.println("The solution to avoid this problem, is to use the backslash escape character.");
        System.out.println("");
        System.out.println("The backslash (\\) escape character turns special characters into string characters:");
        System.out.println("");
        System.out.println("");
        System.out.println("Escape character\tResult\tDescription");
        System.out.println("\\'\t'\tSingle quote");
        System.out.println("");
        System.out.println("\\\"\t\"\tDouble quote");
        System.out.println("");
        System.out.println("\\\\\t\\\tBackslash");
        System.out.println("");
        System.out.println("The sequence \\\"  inserts a double quote in a string:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("String txt = \"We are the so-called \\\"Vikings\\\" from the north.\";");
        System.out.println("");
        System.out.println("");
        System.out.println("The sequence \\'  inserts a single quote in a string:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("String txt = \"It\\'s alright.\";");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("The sequence \\\\  inserts a single backslash in a string:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("String txt = \"The character \\\\ is called backslash.\";");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("Other common escape sequences that are valid in Java are:");
        System.out.println("");
        System.out.println("");
        System.out.println("Code\tResult");
        System.out.println("");
        System.out.println("\\n\tNew Line");
        System.out.println("");
        System.out.println("\\t\tTab");
        System.out.println("");
        System.out.println("\\b\tBackspace");
        System.out.println("");
        System.out.println("\\r\tCarriage Return");
        System.out.println("");
        System.out.println("\\f\tForm Feed");
        System.out.println("");
        System.out.println("");
        System.out.println("");
    }
    
}
