public class Syntaxles {
    
    public static void main(String[] args) {

        System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA SYNTAX");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("Example:");
        System.out.println("");
        System.out.println("");
        System.out.println("Main.java");
        System.out.println("");
        System.out.println("public class Main {");
        System.out.println("  public static void main(String[] args) {");
        System.out.println("    System.out.println(\"Hello World\");");
        System.out.println(" }");
        System.out.println("}");
        System.out.println("");
        System.out.println("");
        System.out.println("Example explained");
        System.out.println("Every line of code that runs in Java must be inside a class.");
        System.out.println("The class name should always start with an uppercase first letter. In our example, we named the class Main.");
        System.out.println("");
        System.out.println("");
        System.out.println("Note: Java is case-sensitive. MyClass and myclass would be treated as two completely different names.");
        System.out.println("");
        System.out.println("The name of the Java file must match the class name. So if your class is called Main, the file must be saved as Main.java.");
        System.out.println("This is because Java uses the class name to find and run your code. ");
        System.out.println(" If the names don't match, Java will give an error and the program will not run.");
        System.out.println("");
        System.out.println("");
        System.out.println("When saving the file, save it using the class name and add .java to the end of the filename. ");
        System.out.println("");
        System.out.println("");
        System.out.println("The main methid ()");
        System.out.println("");
        System.out.println("The main() method is required in every Java program. It is where the program starts running:");
        System.out.println("");
        System.out.println("public static void main(String[] args)");
        System.out.println("");
        System.out.println("");
        System.out.println("Any code placed inside the main() method will be executed.");
        System.out.println("For now, you don't need to understand the keywords public, static, and void. ");
        System.out.println("You will learn about them later in this tutorial. Just remember: main() is the starting point of every Java program.");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("System.out.println()");
        System.out.println("");
        System.out.println("Inside the main() method, we can use the println() method to print a line of text to the screen:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("public static void main(String[] args) {");
        System.out.println("  System.out.println(\"Hello World\");");
        System.out.println("}");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("Note: The curly braces {} mark the beginning and the end of a block of code.");
        System.out.println("System.out.println() may look long, but you can think of it as a single command that means: ");
        System.out.println("\"Send this text to the screen.\"");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("Here's what each part means (you will learn the details later):");
        System.out.println("System is a built-in Java class.");
        System.out.println("out is a member of System, short for \"output\".");
        System.out.println("println() is a method, short for \"print line\".");
        System.out.println("");
        System.out.println("Remember that each Java statement must end with a semicolon (;).");
        System.out.println("");
        System.out.println("");
        System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA STATEMENTS");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("A computer program is a list of \"instructions\" to be \"executed\" by a computer.");
        System.out.println("In a programming language, these programming instructions are called statements.");
        System.out.println("The following statement \"instructs\" the compiler to print the text \"Java is fun!\" to the screen:");
        System.out.println("");
        System.out.println("Example");
        System.out.println("System.out.println(\"Java is fun!\");");
        System.out.println("");
        System.out.println("");
        System.out.println("It is important that you end the statement with a semicolon ;.");
        System.out.println("If you forget the semicolon (;), an error will occur and the program will not run:");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("System.out.println(\"Java is fun!\")");
        System.out.println("");
        System.out.println("error: ';' expected");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("Many Statements");
        System.out.println("");
        System.out.println("Most Java programs contain many statements.");
        System.out.println("");
        System.out.println("The statements are executed, one by one, in the same order as they are written:");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("System.out.println(\"Hello World!\");");
        System.out.println("System.out.println(\"Have a good day!\");");
        System.out.println("System.out.println(\"Learning Java is fun!\");");
        System.out.println("");
        System.out.println("");
        System.out.println("Example explained");
        System.out.println("");
        System.out.println("From the example above, we have three statements:");
        System.out.println("");
        System.out.println("1. System.out.println(\"Hello World!\");");
        System.out.println("2. System.out.println(\"Have a good day!\");");
        System.out.println("3. System.out.println(\"Learning Java is fun!\");");
        System.out.println("");
        System.out.println("");
        System.out.println("The first statement is executed first (print \"Hello World!\" to the screen).");
        System.out.println("Then the second statement is executed (print \"Have a good day!\" to the screen).");
        System.out.println("And at last, the third statement is executed (print \"Learning Java is fun!\" to the screen).");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");





    }
}