public class Booleansles {
    public static void main(String[] args) {
        System.out.println("============================================================================================================================");
        System.out.println("                                                      JAVA BOOLEANS");
        System.out.println("============================================================================================================================");
        System.out.println(" ");
        System.out.println("-Very often in programming, you will need a data type that can only have one of two values like:");
        System.out.println(" ");
        System.out.println("· YES / NO");
        System.out.println("· ON / OFF");
        System.out.println("· TRUE / FALSE");
        System.out.println(" ");
        System.out.println("-For this, Java has a boolean data type, which can store true or false values.");
        System.out.println(" ");
        System.out.println("The name boolean comes from George Boole, a mathematician who first defined");
        System.out.println("the logic system used in computers today.");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Boolean Values");
        System.out.println("-A boolean type is declared with the boolean keyword and can only take the values true or false:");
        System.out.println(" ");
        System.out.println("Example:");
        System.out.println(" ");
        System.out.println("boolean isJavaFun = true;");
        System.out.println("boolean isFishTasty = false;");
        System.out.println("System.out.println(isJavaFun);    // Outputs true");
        System.out.println("System.out.println(isFishTasty);  // Outputs false");
        System.out.println(" ");
        System.out.println("In practice, booleans are most often the result of expressions, and are used to test");
        System.out.println("conditions in programs (see below).");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Boolean Expressions");
        System.out.println(" ");
        System.out.println("-A boolean expression returns a boolean value: true or false.");
        System.out.println(" ");
        System.out.println("-This is useful to build logic and make decisions in programs.");
        System.out.println(" ");
        System.out.println("-For example, you can use a comparison operator, such as the greater than (>) operator, ");
        System.out.println("to find out if an expression (or a variable) is true or false:");
        System.out.println(" ");
        System.out.println("Example: ");
        System.out.println(" ");
        System.out.println("int x = 10;");
        System.out.println("int y = 9;");
        System.out.println("System.out.println(x > y); // returns true, because 10 is greater than 9");
        System.out.println(" ");
        System.out.println("Or even easier:");
        System.out.println(" ");
        System.out.println("Example:");
        System.out.println(" ");
        System.out.println("System.out.println(10 > 9); // returns true, because 10 is greater than 9");
        System.out.println(" ");
        System.out.println("In the examples below, we use the equal to (==) operator to evaluate an expression:");
        System.out.println(" ");
        System.out.println("Example:");
        System.out.println(" ");
        System.out.println("int x = 10;");
        System.out.println("System.out.println(x == 10); // returns true, because the value of x is equal to 10");
        System.out.println(" ");
        System.out.println("Example:");
        System.out.println("System.out.println(10 == 15); // returns false, because 10 is not equal to 15");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Real Life Example");
        System.out.println(" ");
        System.out.println("-Let's think of a \"real life example\" where we need to find out if a person is old enough to vote.");
        System.out.println(" ");
        System.out.println("-In the example below, we use the >= comparison operator to find out if the age (25) is greater");
        System.out.println("than OR equal to the voting age limit, which is set to 18:");
        System.out.println(" ");
        System.out.println("Example:");
        System.out.println("int myAge = 25;");
        System.out.println("int votingAge = 18;");
        System.out.println("System.out.println(myAge >= votingAge);");
        System.out.println(" ");
        System.out.println("An even better approach would be to wrap the code above in an if...else statement,");
        System.out.println("so we can perform different actions depending on the result:");
        System.out.println(" ");
        System.out.println("Example:");
        System.out.println("Output \"Old enough to vote!\" if myAge is greater than or equal to 18. Otherwise output");
        System.out.println("\\\"Not old enough to vote.\\\":");
        System.out.println(" ");
        System.out.println("int myAge = 25;");
        System.out.println("int votingAge = 18;");
        System.out.println(" ");
        System.out.println("if (myAge >= votingAge) {");
        System.out.println("    System.out.println(\"Old enough to vote!\");");
        System.out.println("} else {");
        System.out.println("    System.out.println(\"Not old enough to vote.\");");
        System.out.println("}");
        System.out.println("    ");
        System.out.println("    ");
        System.out.println("Booleans are the basis for all Java comparisons and conditions.");
        System.out.println("    ");
        System.out.println("You will learn more about conditions (if...else) in the next chapter");
        System.out.println("    ");
        System.out.println("    ");

    }
}
