public class Ifelseles {
    public static void main(String[] args) {
        System.out.println("============================================================================================================================");
        System.out.println("                                                      JAVA IF ELSE");
        System.out.println("============================================================================================================================");
        System.out.println(" ");
        System.out.println("Java Conditions and If Statements");
        System.out.println(" ");
        System.out.println("-Conditions and if statements let you control the flow of your program - deciding which code runs, and which code is skipped.");
        System.out.println(" ");
        System.out.println("-Think of it like real life: If it rains, take an umbrella. Otherwise, do nothing.");
        System.out.println(" ");
        System.out.println("-Every if statement needs a condition that results in true or false.");
        System.out.println(" ");
        System.out.println("-This means if statements work hand-in-hand with boolean values:");
        System.out.println(" ");
        System.out.println("Example:");
        System.out.println(" ");
        System.out.println("boolean isRaining = true;");
        System.out.println(" ");
        System.out.println("if (isRaining) {");
        System.out.println("    System.out.println(\"Bring an umbrella!\");");
        System.out.println("}");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("============================================================================================================================");
        System.out.println("                                                      IF STATEMENT");
        System.out.println("============================================================================================================================");
        System.out.println(" ");
        System.out.println("-The if statement specifies a block of code to be executed if a condition is true:");
        System.out.println(" ");
        System.out.println("Syntax:");
        System.out.println(" ");
        System.out.println("if (condition) {");
        System.out.println("    // block of code to be executed if the condition is true");
        System.out.println("}");
        System.out.println(" ");
        System.out.println("Note: The condition inside the if statement must result in a boolean value - it can be either a boolean");
        System.out.println("expression (like x > y) or a boolean variable (like isLightOn).");
        System.out.println(" ");
        System.out.println("Note: Also the if is in lowercase letters. Uppercase letters (If or IF) will generate an error.");
        System.out.println(" ");
        System.out.println("In the example below, we test two values to find out if 20 is greater than 18. If the condition is true, print some text:");
        System.out.println(" ");
        System.out.println("Example:");
        System.out.println(" ");
        System.out.println("if (20 > 18) {");
        System.out.println("    System.out.println(\"20 is greater than 18\");");
        System.out.println("}");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("============================================================================================================================");
        System.out.println("                                                      ELSE STATEMENT");
        System.out.println("============================================================================================================================");
        System.out.println(" ");
        System.out.println("-The else statement lets you run a block of code when the condition in the if statement is false.");
        System.out.println(" ");
        System.out.println("Syntax:");
        System.out.println(" ");
        System.out.println("if (condition) {");
        System.out.println("    // block of code to be executed if the condition is true");
        System.out.println("} else {");
        System.out.println("    // block of code to be executed if the condition is false");
        System.out.println("}");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("This example says good day or good evening depending on the time:");
        System.out.println(" ");
        System.out.println("Example:");
        System.out.println(" ");
        System.out.println("int time = 20;");
        System.out.println(" ");
        System.out.println("if (time < 18) {");
        System.out.println("    System.out.println(\"Good day.\");");
        System.out.println("} else {");
        System.out.println("    System.out.println(\"Good evening.\");");
        System.out.println("}");
        System.out.println("// Outputs \"Good evening.\"");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("============================================================================================================================");
        System.out.println("                                                       ELSE IF STATEMENT");
        System.out.println("============================================================================================================================");
        System.out.println(" ");
        System.out.println("-Use the else if statement to specify a new condition if the first condition is false.");
        System.out.println(" ");
        System.out.println("Syntax");
        System.out.println(" ");
        System.out.println("if (condition1) {");
        System.out.println("    // block of code to be executed if condition1 is true");
        System.out.println("} else if (condition2) {");
        System.out.println("    // block of code to be executed if the condition1 is false and condition2 is true");
        System.out.println("} else {");
        System.out.println("    // block of code to be executed if the condition1 is false and condition2 is false");
        System.out.println("}");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("This example chooses between three different messages depending on the time of day");
        System.out.println(" ");
        System.out.println("Example: ");
        System.out.println("    ");
        System.out.println("int time = 22;");
        System.out.println("if (time < 10) ");
        System.out.println("    System.out.println(\"Good morning.\");");
        System.out.println("} else if (time < 18) {");
        System.out.println("    System.out.println(\"Good day.\");");
        System.out.println("} else {");
        System.out.println("    System.out.println(\"Good evening.\");");
        System.out.println("}");
        System.out.println("// Outputs \"Good evening.\"");
        System.out.println("============================================================================================================================");
        System.out.println("                                                       NESTED IF STATEMENT");
        System.out.println("============================================================================================================================");
        System.out.println(" ");
        System.out.println("-You can also place an if statement inside another if. This is called a nested if statement.");
        System.out.println(" ");
        System.out.println("-A nested if lets you check for a condition only if another condition is already true.");
        System.out.println(" ");
        System.out.println("Syntax:");
        System.out.println(" ");
        System.out.println("if (condition1) {");
        System.out.println("    // code to run if condition1 is true");
        System.out.println("if (condition2) {");
        System.out.println("    // code to run if both condition1 and condition2 are true");
        System.out.println("    }");
        System.out.println("}");
        System.out.println("Example::");
        System.out.println(" ");
        System.out.println("int x = 15;");
        System.out.println("int y = 25;");
        System.out.println(" ");
        System.out.println("if (x > 10) {");
        System.out.println("    System.out.println(\"x is greater than 10\");");
        System.out.println(" ");
        System.out.println("// Nested if ");
        System.out.println("if (y > 20) {");
        System.out.println("    System.out.println(\"y is also greater than 20\");");
        System.out.println("    }");
        System.out.println("}");
        System.out.println(" ");
        System.out.println("Result:");
        System.out.println(" ");
        System.out.println("x is greater than 10");
        System.out.println("y is also greater than 20");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("============================================================================================================================");
        System.out.println("                                                 LOGICAL OPERATORS IN CONDITION");
        System.out.println("============================================================================================================================");
        System.out.println(" ");
        System.out.println("-You can combine or reverse conditions using logical operators. These work together with if, else,");
        System.out.println("and else if to build more complex decisions.");
        System.out.println(" ");
        System.out.println("· && (AND) - all conditions must be true");
        System.out.println("· || (OR) - at least one condition must be true");
        System.out.println("· ! (NOT) - reverses a condition (true = false, false = true)");
        System.out.println(" ");
        System.out.println("AND (&&)");
        System.out.println(" ");
        System.out.println("-Use AND (&&) when both conditions must be true:");
        System.out.println(" ");
        System.out.println("Example:");
        System.out.println(" ");
        System.out.println("Test if a is greater than b, and if c is greater than a:");
        System.out.println("    ");
        System.out.println("int a = 200;");
        System.out.println("int b = 33;");
        System.out.println("int c = 500;");
        System.out.println(" ");
        System.out.println("if (a > b && c > a) {");
        System.out.println("    System.out.println(\"Both conditions are true\");");
        System.out.println("}");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("OR (||)");
        System.out.println(" ");
        System.out.println("-Use OR (||) when at least one of the conditions can be true:");
        System.out.println(" ");
        System.out.println("Example:");
        System.out.println(" ");
        System.out.println("Test if a is greater than b, or if a is greater than c:");
        System.out.println(" ");
        System.out.println("int a = 200;");
        System.out.println("int b = 33;");
        System.out.println("int c = 500;");
        System.out.println(" ");
        System.out.println("if (a > b || a > c) {");
        System.out.println("    System.out.println(\"At least one condition is true\");");
        System.out.println("}");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("NOT (!)");
        System.out.println(" ");
        System.out.println("-Use NOT (!) to reverse a condition:");
        System.out.println(" ");
        System.out.println("Example:");
        System.out.println(" ");
        System.out.println("Test if a is not greater than b");
        System.out.println(" ");
        System.out.println("int a = 33;");
        System.out.println("int b = 200;");
        System.out.println("    ");
        System.out.println("if (!(a > b)) {");
        System.out.println("    System.out.println(\"a is NOT greater than b\");");
        System.out.println("}");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Real-Life Example");
        System.out.println(" ");
        System.out.println("-In real programs, logical operators are often used for access control. For example,");
        System.out.println("to get access to a system, there are specific requirements:");
        System.out.println(" ");
        System.out.println("-You must be logged in, and then you either need to be an admin, or have a high security clearance (level 1 or 2)");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Example:");
        System.out.println(" ");
        System.out.println("boolean isLoggedIn = true;");
        System.out.println("boolean isAdmin = false;");
        System.out.println("int securityLevel = 3; // 1 = highest");
        System.out.println(" ");
        System.out.println("if (isLoggedIn && (isAdmin || securityLevel <= 2)) {");
        System.out.println("    System.out.println(\"Access granted\");");
        System.out.println("} else {");
        System.out.println("    System.out.println(\"Access denied\");");
        System.out.println("}");
        System.out.println(" ");
        System.out.println("// Try changing securityLevel to test different outcomes:");
        System.out.println("//");
        System.out.println("// securityLevel 1 = Access granted");
        System.out.println("// securityLevel 2 = Access granted");
        System.out.println("// securityLevel 3 = Access denied");
        System.out.println("// securityLevel 4 = Access denied");
        System.out.println("//");
        System.out.println("// If isAdmin = true, access is granted.");
        System.out.println(" ");
        System.out.println(" ");
    }
}

