public class Mathles{
    public static void main(String[] args) {
        System.out.println("============================================================================================================================");
        System.out.println("                                                      JAVA MATH");
        System.out.println("============================================================================================================================");
        System.out.println(" ");
        System.out.println("-The Java Math class has many methods that allows you to perform mathematical tasks on numbers.");
        System.out.println(" ");
        System.out.println("Math.max(x,y)");
        System.out.println(" ");
        System.out.println("-The Math.max(x,y) method can be used to find the highest value of x and y:");
        System.out.println(" ");
        System.out.println("Example: Math.max(5, 10);");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Math.min(x,y)");
        System.out.println(" ");
        System.out.println("-The Math.min(x,y) method can be used to find the lowest value of x and y:");
        System.out.println(" ");
        System.out.println("Example: Math.min(5, 10);");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Math.sqrt(x)");
        System.out.println("The Math.sqrt(x) method returns the square root of x:");
        System.out.println(" ");
        System.out.println("Example: Math.sqrt(64);");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Math.abs(x)");
        System.out.println(" ");
        System.out.println("-The Math.abs(x) method returns the absolute (positive) value of x:");
        System.out.println(" ");
        System.out.println("Example: Math.abs(-4.7);");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Math.pow(x, y)");
        System.out.println(" ");
        System.out.println("-The Math.pow(x, y) method returns the value of x raised to the power of y:");
        System.out.println("Example: Math.pow(2, 8);  // 256.0");
        System.out.println(" ");
        System.out.println("Note: Math.pow(2, 8) means 2 multiplied by itself 8 times:");
        System.out.println("2 * 2 * 2 * 2 * 2 * 2 * 2 * 2 = 256");
        System.out.println(" ");
        System.out.println("Note: The Math.pow() method always returns a double, even if the result is");
        System.out.println("a whole number. For example, Math.pow(2, 8) returns 256.0 (not 256).");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Rounding Methods");
        System.out.println("Java has several methods for rounding numbers:");
        System.out.println("· Math.round(x) - rounds to the nearest integer");
        System.out.println("· Math.ceil(x) - rounds up (returns the smallest integer greater than or equal to x)");
        System.out.println("· Math.floor(x) - rounds down (returns the largest integer less than or equal to x)");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Example:");
        System.out.println("Math.round(4.6);  // 5");
        System.out.println("Math.ceil(4.1);   // 5.0");
        System.out.println("Math.floor(4.9);  // 4.0");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Random Numbers");
        System.out.println(" ");
        System.out.println("- Math.random() returns a random number between 0.0 (inclusive), and 1.0 (exclusive):");
        System.out.println(" ");
        System.out.println("Example: Math.random();");
        System.out.println(" ");
        System.out.println("To get more control over the random number, for example, if you only want a random");
        System.out.println("number between 0 and 100, you can use the following formula:");
        System.out.println(" ");
        System.out.println("Example: int randomNum = (int)(Math.random() * 101);  // 0 to 100");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Note: Math.random() returns a double. To get an integer, you need to cast it with (int)");
        System.out.println(" ");
        System.out.println(" ");

    }
}