public class Operales {
    public static void main(String[] args) {

        System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA OPERATORS");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("Operators are used to perform operations on variables and values.");
        System.out.println("");
        System.out.println("In the example below, we use the + operator to add together two values:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int x = 100 + 50;");
        System.out.println("");
        System.out.println("");
        System.out.println("Although the + operator is often used to add together two values, like in the example above,");
        System.out.println("it can also be used to add together a variable and a value, or a variable and another variable:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int sum1 = 100 + 50;        // 150 (100 + 50)");
        System.out.println("int sum2 = sum1 + 250;      // 400 (150 + 250)");
        System.out.println("int sum3 = sum2 + sum2;     // 800 (400 + 400)");
         System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA ARITHMETIC OPERATORS");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("Arithmetic operators are used to perform common mathematical operations.");
        System.out.println("");
        System.out.println("Operator\tName\tDescription\tExample");
        System.out.println("");
        System.out.println("+\tAddition\tAdds together two values\tx + y");
        System.out.println("");
        System.out.println("-\tSubtraction\tSubtracts one value from another\tx - y");
        System.out.println("");
        System.out.println("*\tMultiplication\tMultiplies two values\tx * y");
        System.out.println("");
        System.out.println("/\tDivision\tDivides one value by another\tx / y");
        System.out.println("");
        System.out.println("%\tModulus\tReturns the division remainder\tx % y");
        System.out.println("");
        System.out.println("++\tIncrement\tIncreases the value of a variable by 1\t++x");
        System.out.println("");
        System.out.println("--\tDecrement\tDecreases the value of a variable by 1\t--x");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("Here is an example using different arithmetic operators in one example:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int x = 10;");
        System.out.println("int y = 3;");
        System.out.println("");
        System.out.println("System.out.println(x + y); // 13");
        System.out.println("System.out.println(x - y); // 7");
        System.out.println("System.out.println(x * y); // 30");
        System.out.println("System.out.println(x / y); // 3");
        System.out.println("System.out.println(x % y); // 1");
        System.out.println("");
        System.out.println("int z = 5;");
        System.out.println("++z;");
        System.out.println("System.out.println(z); // 6");
        System.out.println("--z;");
        System.out.println("");
        System.out.println("System.out.println(z); // 5");
        System.out.println("");
        System.out.println("");
        System.out.println("Note: When dividing two integers in Java, the result will also be an integer. For example, 10 / 3 gives 3.");
        System.out.println("If you want a decimal result, use double values, like 10.0 / 3.");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("");
        System.out.println("int a = 10;");
        System.out.println("int b = 3;");
        System.out.println("System.out.println(a / b);   // Integer division, result is 3");
        System.out.println("");
        System.out.println("double c = 10.0d;");
        System.out.println("double d = 3.0d;");
        System.out.println("System.out.println(c / d);   // Decimal division, result is 3.333...");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("Incrementing and Decrementing");
        System.out.println("");
        System.out.println("Incrementing and decrementing are very common in programming, especially when working with counters,");
        System.out.println("loops, and arrays (which you will learn more about in later chapters).");
        System.out.println("");
        System.out.println("The ++ operator increases a value by 1, while the -- operator decreases a value by 1:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int x = 5;");
        System.out.println("");
        System.out.println("++x; // Increment x by 1");
        System.out.println("System.out.println(x); // 6");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int x = 5;");
        System.out.println("");
        System.out.println("--x; // Decrement x by 1");
        System.out.println("System.out.println(x); // 4");
        System.out.println("");
        System.out.println("");
        System.out.println("Sometimes, you might both increment and decrement the same variable. Remember that if you increase a value and later decrease it,");
        System.out.println("it will go up by one and then back down by one - ending up where it started:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int x = 5;");
        System.out.println("");
        System.out.println("++x; // Increment x by 1 (x becomes 6)");
        System.out.println("--x; // Decrement x by 1 (x becomes 5 again)");
        System.out.println("");
        System.out.println("System.out.println(x); // 5");
        System.out.println("");
        System.out.println("");
        System.out.println("Real Life Example: Counting People");
        System.out.println("");
        System.out.println("Imagine you are building a program to count how many people enter and leave a room. ");
        System.out.println("You can use ++ to increase the counter when someone enters, and -- to decrease it when someone leaves:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int peopleInRoom = 0;");
        System.out.println("");
        System.out.println("// 3 people enter");
        System.out.println("peopleInRoom++;");
        System.out.println("peopleInRoom++;");
        System.out.println("peopleInRoom++;");
        System.out.println("");
        System.out.println("System.out.println(peopleInRoom); // 3");
        System.out.println("");
        System.out.println("// 1 person leaves");
        System.out.println("peopleInRoom--;");
        System.out.println("");
        System.out.println("System.out.println(peopleInRoom); // 2");
        System.out.println("");
        System.out.println("");
        System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA ASSIGNMENT OPERATORS");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("Assignment operators are used to assign values to variables.");
        System.out.println("");
        System.out.println("In the example below, we use the assignment operator (=) to assign the value 10 to a variable called x:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int x = 10;");
        System.out.println("");
        System.out.println("");
        System.out.println("The addition assignment operator (+=) adds a value to a variable:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int x = 10;");
        System.out.println("x += 5;");
        System.out.println("");
        System.out.println("");
        System.out.println("A list of all assignment operators:");
        System.out.println("");
        System.out.println("");
        System.out.println("Operator\tExample\tSame As");
        System.out.println("");
        System.out.println("=\tx = 5\tx = 5");
        System.out.println("");
        System.out.println("+=\tx += 3\tx = x + 3");
        System.out.println("");
        System.out.println("-=\tx -= 3\tx = x - 3");
        System.out.println("");
        System.out.println("*=\tx *= 3\tx = x * 3");
        System.out.println("");
        System.out.println("/=\tx /= 3\tx = x / 3");
        System.out.println("");
        System.out.println("%=\tx %= 3\tx = x % 3");
        System.out.println("");
        System.out.println("&=\tx &= 3\tx = x & 3");
        System.out.println("");
        System.out.println("|=\tx |= 3\tx = x | 3");
        System.out.println("");
        System.out.println("^=\tx ^= 3\tx = x ^ 3");
        System.out.println("");
        System.out.println(">>=\tx >>= 3\tx = x >> 3");
        System.out.println("");
        System.out.println("<<=\tx <<= 3\tx = x << 3");
        System.out.println("");
        System.out.println("");
        System.out.println("Note: Most assignment operators are just shorter ways of writing code. For example, ");
        System.out.println("x += 5 is the same as x = x + 5, but shorter and often easier to read.");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("Real-Life Example: Tracking Savings");
        System.out.println("");
        System.out.println("Assignment operators can also be used in real-life scenarios. ");
        System.out.println("For example, you can use the += operator to keep track of savings when you add money to an account:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int savings = 100; ");
        System.out.println("savings += 50; // add 50 to savings");
        System.out.println("System.out.println(\"Total savings: \" + savings);");
        System.out.println("");
        System.out.println("");
         System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA COMPARISON OPERATORS");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("Comparison operators are used to compare two values (or variables). This is important in programming,");
        System.out.println("because it helps us to find answers and make decisions.");
        System.out.println("");
        System.out.println("The return value of a comparison is either true or false. These values are known as Boolean values, ");
        System.out.println("and you will learn more about them in the Booleans and If..Else chapter.");
        System.out.println("");
        System.out.println("In the following example, we use the greater than operator (>) to find out if 5 is greater than 3:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int x = 5;");
        System.out.println("int y = 3;");
        System.out.println("System.out.println(x > y); // returns true, because 5 is higher than 3");
        System.out.println("");
        System.out.println("");
        System.out.println("A list of all comparison operators:");
        System.out.println("");
        System.out.println("");
        System.out.println("Operator\tName\tExample");
        System.out.println("");
        System.out.println("==\tEqual to\tx == y");
        System.out.println("");
        System.out.println("!=\tNot equal\tx != y");
        System.out.println("");
        System.out.println(">\tGreater than\tx > y");
        System.out.println("");
        System.out.println("<\tLess than\tx < y");
        System.out.println("");
        System.out.println(">=\tGreater than or equal to\tx >= y");
        System.out.println("");
        System.out.println("<=\tLess than or equal to\tx <= y");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("Real-Life Examples");
        System.out.println("");
        System.out.println("Comparison operators are often used in real-world conditions, such as checking if a person is old enough to vote:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int age = 18;");
        System.out.println("");
        System.out.println("System.out.println(age >= 18); // true, old enough to vote");
        System.out.println("System.out.println(age < 18);  // false, not old enough");
        System.out.println("");
        System.out.println("Another common use is checking if a password is long enough:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int passwordLength = 5;");
        System.out.println("");
        System.out.println("System.out.println(passwordLength >= 8); // false, too short");
        System.out.println("System.out.println(passwordLength < 8);  // true, needs more characters");
        System.out.println("");
        System.out.println("");
         System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA LOGICAL OPERATORS");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("As with comparison operators, you can also test for true or false values with logical operators.");
        System.out.println("");
        System.out.println("Logical operators are used to determine the logic between variables or values, by combining multiple conditions::");
        System.out.println("");
        System.out.println("");
        System.out.println("Operator\tName\tDescription                                         Example");
        System.out.println("");
        System.out.println("&& \tLogical and\tReturns true if both statements are true\tx < 5 &&  x < 10");
        System.out.println("");
        System.out.println("|| \tLogical or\tReturns true if one of the statements is true\tx < 5 || x < 4");
        System.out.println("");
        System.out.println("!\tLogical not\tReverse the result, returns false if the result is true\t!(x < 5 && x < 10)");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
    }
    
}
