public class Outples {
    public static void main(String[] args) {
        System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA OUTPUT");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("Print Text");
        System.out.println("You learned from the previous chapter that you can use the println() method to output values or print text in Java:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("System.out.println(\"Hello World!\");");
        System.out.println("");
        System.out.println("");
        System.out.println("You can add as many println() methods as you want. Note that it will add a new line for each method:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("System.out.println(\"Hello World!\");");
        System.out.println("System.out.println(\"I am learning Java.\");");
        System.out.println("System.out.println(\"It is awesome!\");");
        System.out.println("");
        System.out.println("");
        System.out.println("Double Quotes");
        System.out.println();
        System.out.println("Text must be wrapped inside double quotations marks \"\"");
        System.out.println("");
        System.out.println("If you forget the double quotes, an error occurs");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("System.out.println(\"This sentence will work!\");");
        System.out.println("System.out.println(This sentence will produce an error);");
        System.out.println("");
        System.out.println("");
        System.out.println("The Print() Method");
        System.out.println("");
        System.out.println("There is also a print() method, which is similar to println().");
        System.out.println("");
        System.out.println("The only difference is that it does not insert a new line at the end of the output:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("System.out.print(\"Hello World! \");");
        System.out.println("System.out.print(\"I will print on the same line.\");");
        System.out.println("");
        System.out.println("");
        System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA PRINT NUMBERS");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("You can also use the println() method to print numbers.");
        System.out.println("");
        System.out.println("However, unlike text, we don't put numbers inside double quotes:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("System.out.println(3);");
        System.out.println("System.out.println(358);");
        System.out.println("System.out.println(50000);");
        System.out.println("");
        System.out.println("");
        System.out.println("You can also perform mathematical calculations inside the println() method:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("System.out.println(3 + 3);");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("System.out.println(2 * 5);");
        System.out.println("");
        System.out.println("");
    }    
    
}
