public class Switchles {
    public static void main(String[] args) {
        System.out.println("============================================================================================================================");
        System.out.println("                                                      JAVA SWITCH");
        System.out.println("============================================================================================================================");
        System.out.println(" ");
        System.out.println("Java Switch Statements");
        System.out.println(" ");
        System.out.println("-Instead of writing many if..else statements, you can use the switch statement.");
        System.out.println(" ");
        System.out.println("-Think of it like ordering food in a restaurant: If you choose number 1, you get Pizza. If you choose 2,");
        System.out.println("you get a Burger. If you choose 3, you get Pasta. Otherwise, you get nothing.");
        System.out.println(" ");
        System.out.println("-The switch statement selects one of many code blocks to be executed:");
        System.out.println(" ");
        System.out.println("Syntax:");
        System.out.println(" ");
        System.out.println("switch(expression) {");
        System.out.println("    case x:");
        System.out.println("        // code block");
        System.out.println("        break;");
        System.out.println("    case y:");
        System.out.println("        // code block ");
        System.out.println("        break;");
        System.out.println("    default: ");
        System.out.println("        // code block  ");
        System.out.println("}");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("This is how it works:");
        System.out.println(" ");
        System.out.println("· The switch expression is evaluated once.");
        System.out.println("· The result is compared with each case value.");
        System.out.println("· If there is a match, the matching block of code runs.");
        System.out.println("· The break statement stops the switch after the matching case has run.");
        System.out.println("· The default statement runs if there is no match.");
        System.out.println(" ");
        System.out.println("The example below uses the weekday number to calculate the weekday name:");
        System.out.println(" ");
        System.out.println("Example:");
        System.out.println(" ");
        System.out.println("int day = 4;");
        System.out.println("switch (day) {");
        System.out.println("    case 1:");
        System.out.println("        System.out.println(\"Monday\");");
        System.out.println("        break;");
        System.out.println("    case 2:");
        System.out.println("        System.out.println(\"Tuesday\");");
        System.out.println("        break;");
        System.out.println("    case 3:");
        System.out.println("        System.out.println(\"Wednesday\");");
        System.out.println("        break;");
        System.out.println("    case 4:");
        System.out.println("        System.out.println(\"Thursday\");");
        System.out.println("        break;");
        System.out.println("    case 5:");
        System.out.println("        System.out.println(\"Friday\");");
        System.out.println("        break;");
        System.out.println("    case 6:");
        System.out.println("        System.out.println(\"Saturday\");");
        System.out.println("        break;");
        System.out.println("    case 7:");
        System.out.println("        System.out.println(\"Sunday\");");
        System.out.println("        break;");
        System.out.println("}");
        System.out.println("// Outputs \"Thursday\" (day 4)");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Note: if the default statement is used as the last statement in a switch block, it does not need a break.)");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("The break Keyword");
        System.out.println("-When Java reaches a break keyword, it breaks out of the switch block.");
        System.out.println(" ");
        System.out.println("-This will stop the execution of more code and case testing inside the block.");
        System.out.println(" ");
        System.out.println("-When a match is found, and the job is done, it's time for a break. There is no need for more testing.");
        System.out.println(" ");
        System.out.println("Note: A break can save a lot of execution time because it \"ignores\" the execution of all the rest of the code in the switch block.");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("The default Keyword");
        System.out.println(" ");
        System.out.println("-The default keyword specifies some code to run if there is no case match:");
        System.out.println(" ");
        System.out.println("Example:");
        System.out.println(" ");
        System.out.println("int day = 4;");
        System.out.println("switch (day) {");
        System.out.println("    case 6:");
        System.out.println("        System.out.println(\"Today is Saturday\");");
        System.out.println("        break;");
        System.out.println("    case 7:");
        System.out.println("        System.out.println(\"Today is Sunday\");");
        System.out.println("        break;");
        System.out.println("    default:");
        System.out.println("        System.out.println(\"Looking forward to the Weekend\");");
        System.out.println("}");
        System.out.println("// Outputs \"Looking forward to the Weekend\"");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Note that if the default statement is used as the last statement in a switch block, it does not need a break.");
        System.out.println(" ");
        System.out.println(" ");
    }
}
