public class Arrayles {
    public static void main(String[] args) {
        System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA ARRAYS");
        System.out.println("============================================================================================================================");
        System.out.println(" ");
        System.out.println("- Arrays are used to store multiple values in a single variable, instead of declaring separate variables for each value.");
        System.out.println(" ");
        System.out.println("To declare an array, define the variable type with square brackets [ ] :");
        System.out.println("  ");
        System.out.println("Example: String[] cars;");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("We have now declared a variable that holds an array of strings. To insert values to it, you can place the");
        System.out.println("values in a comma-separated list, inside curly braces { }:");
        System.out.println(" ");
        System.out.println("Example: String[] cars = {\"Volvo\", \"BMW\", \"Ford\", \"Mazda\"};");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("To create an array of integers, you could write:");
        System.out.println(" ");
        System.out.println("Example: int[] myNum = {10, 20, 30, 40};");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Access the Elements of an Array");
        System.out.println(" ");
        System.out.println("- You can access an array element by referring to the index number.");
        System.out.println(" ");
        System.out.println("This statement accesses the value of the first element in cars:");
        System.out.println(" ");
        System.out.println("Example: ");
        System.out.println(" ");
        System.out.println("String[] cars = {\"Volvo\", \"BMW\", \"Ford\", \"Mazda\"};");
        System.out.println("System.out.println(cars[0]);");
        System.out.println("// Output : Volvo");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Note: Array indexes start with 0: [0] is the first element. [1] is the second element, etc.");
        System.out.println(" ");
        System.out.println("Think of an array as numbered boxes, where each box stores an element:");
        System.out.println(" ");
        System.out.println("Index       Element");
        System.out.println("  0           Volvo  ");
        System.out.println("  1            BMW  ");
        System.out.println("  2           Ford  ");
        System.out.println("  3           Mazda  ");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Change an Array Element");
        System.out.println(" ");
        System.out.println("To change the value of a specific element, refer to the index number:");
        System.out.println(" ");
        System.out.println("EXample: ");
        System.out.println(" ");
        System.out.println("String[] cars = {\"Volvo\", \"BMW\", \"Ford\", \"Mazda\"};");
        System.out.println("cars[0] = \"Opel\";");
        System.out.println("System.out.println(cars[0]);");
        System.out.println("// Now outputs Opel instead of Volvo");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Array Length");
        System.out.println(" ");
        System.out.println("To find out how many elements an array has, use the length property:");
        System.out.println(" ");
        System.out.println("Example: ");
        System.out.println(" ");
        System.out.println("String[] cars = {\"Volvo\", \"BMW\", \"Ford\", \"Mazda\"};");
        System.out.println("System.out.println(cars.length);");
        System.out.println("// Outputs 4");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Loop Through an Array");
        System.out.println(" ");
        System.out.println("- You can loop through the array elements with the for loop, and use the length property");
        System.out.println("  to specify how many times the loop should run.");
        System.out.println(" ");
        System.out.println("This example creates an array of strings and then uses a for loop to print each element, one by one:");
        System.out.println(" ");
        System.out.println("Example: ");
        System.out.println(" ");
        System.out.println("String[] cars = {\"Volvo\", \"BMW\", \"Ford\", \"Mazda\"};");
        System.out.println(" ");
        System.out.println("for (int i = 0; i < cars.length; i++) {");
        System.out.println("    System.out.println(cars[i]);");
        System.out.println("}");
        System.out.println(" ");
        System.out.println(" ");

    }
}
