public class Whileles {
    public static void main(String[] args) {
        System.out.println("=========================================================================================================================");
        System.out.println("                                                      JAVA WHILE LOOP");
        System.out.println("=========================================================================================================================");
        System.out.println(" ");
        System.out.println("Loops");
        System.out.println(" ");
        System.out.println("-Loops can execute a block of code as long as a specified condition is true.");
        System.out.println(" ");
        System.out.println("-Loops are handy because they save time, reduce errors, and they make code more readable.");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Java While Loop");
        System.out.println(" ");
        System.out.println("-The while loop repeats a block of code as long as the specified condition is true:");
        System.out.println(" ");
        System.out.println("Syntax:");
        System.out.println(" ");
        System.out.println("while (condition) {");
        System.out.println("    // code block to be executed");
        System.out.println("}");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("In the example below, the code in the loop will run again and again, as long as a variable (i) is less than 5:");
        System.out.println(" ");
        System.out.println("Example:");
        System.out.println(" ");
        System.out.println("int i = 0");
        System.out.println("while (i < 5) {");
        System.out.println("    System.out.println(i);");
        System.out.println("    i++;");
        System.out.println("}");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Note: Do not forget to increase the variable used in the condition (i++), otherwise the loop will never end!");
        System.out.println(" ");
        System.out.println("Do you wonder why we used the letter i in the example above? It's a counter variable and a common choice");
        System.out.println("in simple loops because it's short, traditional, and stands for 'index' or 'iterator'.");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("=========================================================================================================================");
        System.out.println("                                                      JAVA DO/WHILE LOOP");
        System.out.println("=========================================================================================================================");
        System.out.println(" ");
        System.out.println("-The do/while loop is a variant of the while loop. This loop will execute the code block once, before checking if");
        System.out.println("the condition is true. Then it will repeat the loop as long as the condition is true.");
        System.out.println(" ");
        System.out.println("Syntax:");
        System.out.println(" ");
        System.out.println("do{");
        System.out.println("    // code block to be executed");
        System.out.println("}");
        System.out.println("while (condition);");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Note: The semicolon ; after the while condition is required!");
        System.out.println("  ");
        System.out.println(" ");
        System.out.println("Do/While Example");
        System.out.println(" ");
        System.out.println("-The example below uses a do/while loop. The loop will always be executed at least once, even if the");
        System.out.println("condition is false, because the code block is executed before the condition is tested:");
        System.out.println(" ");
        System.out.println("Example:");
        System.out.println(" ");
        System.out.println("int i = 0;");
        System.out.println("do {");
        System.out.println("    System.out.println(i);");
        System.out.println("    i++;");
        System.out.println("}");
        System.out.println("while (i < 5);");
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("Note: Do not forget to increase the variable used in the condition (i++), otherwise the loop will never end!");
        System.out.println(" ");
        System.out.println(" ");
    }
}

