public class Varles {
    public static void main(String[] args) {
        
        System.out.println("");
        System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA VARIABLES");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("Variables are containers for storing data values.");
        System.out.println("");
        System.out.println("In Java, there are different types of variables, for example:");
        System.out.println("");
        System.out.println("String - stores text, such as \"Hello\". String values are surrounded by double quotes");
        System.out.println("int - stores integers (whole numbers), without decimals, such as 123 or -123");
        System.out.println("float - stores floating point numbers, with decimals, such as 19.99 or -19.99");
        System.out.println("char - stores single characters, such as 'a' or 'B'. Char values are surrounded by single quotes");
        System.out.println("boolean - stores values with two states: true or false");
        System.out.println("");
        System.out.println("");
        System.out.println("Declaring (Creating) Variables");
        System.out.println("");
        System.out.println("To create a variable in Java, you need to:");
        System.out.println("");
        System.out.println("Choose a type (like int or String)");
        System.out.println("Give the variable a name (like x, age, or name)");
        System.out.println("Optionally assign it a value using =");
        System.out.println("");
        System.out.println("");
        System.out.println("Here's the basic syntax:");
        System.out.println("");
        System.out.println("Syntax");
        System.out.println("");
        System.out.println("type variableName = value;");
        System.out.println("");
        System.out.println("");
        System.out.println("For example, if you want to store some text, you can use a String:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("Create a variable called name of type String and assign it the value \"John\".");
        System.out.println("Then we use println() to print the name variable:");
        System.out.println("");
        System.out.println("String name = \"John\";");
        System.out.println("System.out.println(name);");
        System.out.println("");
        System.out.println("");
        System.out.println("To create a variable that should store a number, you can use int:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("Create a variable called myNum of type int and assign it the value 15:");
        System.out.println("");
        System.out.println("int myNum = 15;");
        System.out.println("System.out.println(myNum);");
        System.out.println("");
        System.out.println("");
        System.out.println("You can also declare a variable without assigning the value, and assign the value later:");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int myNum;");
        System.out.println("myNum = 15;");
        System.out.println("System.out.println(myNum);");
        System.out.println("");
        System.out.println("");
        System.out.println("Note that if you assign a new value to an existing variable, it will overwrite the previous value:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("Change the value of myNum from 15 to 20:");
        System.out.println("");
        System.out.println("int myNum = 15;");
        System.out.println("myNum = 20;  // myNum is now 20");
        System.out.println("System.out.println(myNum);");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("Final Variables");
        System.out.println("");
        System.out.println("If you don't want others (or yourself) to overwrite existing values, use the final keyword ");
        System.out.println("(this will declare the variable as \"final\" or \"constant\", which means unchangeable and read-only):");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("final int myNum = 15;");
        System.out.println("myNum = 20;  // will generate an error: cannot assign a value to a final variable");
        System.out.println("");
        System.out.println("");
        System.out.println("Other Types");
        System.out.println("");
        System.out.println("A demonstration of how to declare variables of other types:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int myNum = 5;");
        System.out.println("float myFloatNum = 5.99f;");
        System.out.println("char myLetter = 'D';");
        System.out.println("boolean myBool = true;");
        System.out.println("String myText = \"Hello\";");
        System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA DISPLAY VARIABLES");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("The println() method is often used to display variables.");
        System.out.println("");
        System.out.println("To combine both text and a variable, use the + character:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("String name = \"John\";");
        System.out.println("System.out.println(\"Hello \" + name);");
        System.out.println("");
        System.out.println("");
        System.out.println("You can also use the + character to add a variable to another variable:");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("String firstName = \"John \";");
        System.out.println("String lastName = \"Doe\";");
        System.out.println("String fullName = firstName + lastName;");
        System.out.println("System.out.println(fullName);");
        System.out.println("");
        System.out.println("");
        System.out.println("In Java, the + symbol has two meanings:");
        System.out.println("");
        System.out.println("For text (strings), it joins them together (called concatenation).");
        System.out.println("For numbers, it adds values together.");
        System.out.println("");
        System.out.println("For numeric values, the + character works as a mathematical operator (notice that we use int (integer) variables here):");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int x = 5;");
        System.out.println("int y = 6;");
        System.out.println("System.out.println(x + y); // Print the value of x + y");
        System.out.println("");
        System.out.println("");
        System.out.println("From the example above, here's what happens step by step:");
        System.out.println("x stores the value 5");
        System.out.println("y stores the value 6");
        System.out.println("println() displays the result of x + y, which is 11");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("Mixing Text and Numbers");
        System.out.println("");
        System.out.println("Be careful when combining text and numbers in the same line of code. Without parentheses, ");
        System.out.println("Java will treat the numbers as text after the first string:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int x = 5;");
        System.out.println("int y = 6;");
        System.out.println("");
        System.out.println("System.out.println(\"The sum is \" + x + y);   // Prints: The sum is 56");
        System.out.println("System.out.println(\"The sum is \" + (x + y)); // Prints: The sum is 11");
        System.out.println("");
        System.out.println("");
        System.out.println("Explanation:");
        System.out.println("");
        System.out.println("In the first line, Java combines \"The sum is \" with x,");
        System.out.println("creating the string \"The sum is 5\"");
        System.out.println("Then y is added to that string, so it becomes \"The sum is 56\".");
        System.out.println("");
        System.out.println("In the second line, the parentheses make sure x + y is calculated first (resulting in 11),");
        System.out.println("so the output is \"The sum is 11\".");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA MULTIPLE VARIABLES");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("Declare Many Variables");
        System.out.println("");
        System.out.println("To declare more than one variable of the same type, you can use a comma-separated list:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("Instead of writing:");
        System.out.println("");
        System.out.println("int x = 5;");
        System.out.println("int y = 6;");
        System.out.println("int z = 50;");
        System.out.println("System.out.println(x + y + z); // 61");
        System.out.println("");
        System.out.println("You can write:");
        System.out.println("");
        System.out.println("int x = 5, y = 6, z = 50;");
        System.out.println("System.out.println(x + y + z); // 61");
        System.out.println("");
        System.out.println("");
        System.out.println("Note: Declaring many variables in one line is shorter, ");
        System.out.println("but writing one variable per line can sometimes make the code easier to read.");
        System.out.println("");
        System.out.println("");
        System.out.println("One Value to Multiple Variables");
        System.out.println("");
        System.out.println("You can also assign the same value to multiple variables in one line:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("int x, y, z;");
        System.out.println("x = y = z = 50;");
        System.out.println("System.out.println(x + y + z); // 150");
        System.out.println("");
        System.out.println("");
        System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA IDENTIFIERS");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("All Java variables must be identified with unique names.");
        System.out.println("These unique names are called identifiers.");
        System.out.println("Identifiers can be short names (like x and y) or more descriptive names (age, sum, totalVolume).");
        System.out.println("");
        System.out.println("Note: It is recommended to use descriptive names in order to create understandable and maintainable code:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("// Good");
        System.out.println("int minutesPerHour = 60;");
        System.out.println("");
        System.out.println("// OK, but not so easy to understand what m actually is");
        System.out.println("int m = 60;");
        System.out.println("");
        System.out.println("");
        System.out.println("The general rules for naming variables are:");
        System.out.println("");
        System.out.println("Names can contain letters, digits, underscores, and dollar signs");
        System.out.println("Names must begin with a letter");
        System.out.println("Names should start with a lowercase letter, and cannot contain whitespace");
        System.out.println("Names can also begin with $ and _");
        System.out.println("Names are case-sensitive (\"myVar\" and \"myvar\" are different variables)");
        System.out.println("Reserved words (like Java keywords, such as int or boolean) cannot be used as names");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("Invalid Identifiers");
        System.out.println("");
        System.out.println("Here are some examples of invalid identifiers that would cause errors:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("// Invalid identifiers:");
        System.out.println("int 2ndNumber = 5;  // Cannot start with a digit");
        System.out.println("int my var = 10;    // Cannot contain spaces");
        System.out.println("int int = 20;       // Cannot use reserved keywords");
        System.out.println("");
        System.out.println("");
        System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA CONSTANT (final)");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("When you do not want a variable's value to change, use the final keyword.");
        System.out.println("A variable declared with final becomes a constant, which means unchangeable and read-only:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("final int myNum = 15;");
        System.out.println("myNum = 20;  // Error: cannot assign a value to final variable 'myNum'");
        System.out.println("");
        System.out.println("");
        System.out.println("When to Use final?");
        System.out.println("");
        System.out.println("You should declare variables as final when their values should never change. ");
        System.out.println("");
        System.out.println("For example, the number of minutes in an hour, or your birth year:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("final int MINUTES_PER_HOUR = 60;");
        System.out.println("final int BIRTHYEAR = 1980;");
        System.out.println("");
        System.out.println("Note: By convention, final variables in Java are usually written in upper case (e.g. BIRTHYEAR). ");
        System.out.println("It is not required, but useful for code readability and common for many programmers.");
        System.out.println("");
        System.out.println("");
        System.out.println("============================================================================================================================");
        System.out.println("                                                 JAVA VARIABLES EXAMPLES");
        System.out.println("============================================================================================================================");
        System.out.println("");
        System.out.println("Often in our examples, we simplify variable names to match their data type (myInt or myNum for int types,");
        System.out.println("myChar for char types, and so on). This is done to avoid confusion.");
        System.out.println("");
        System.out.println("However, for a practical example of using variables, we have created a program that stores different data about a college student:");
        System.out.println("");
        System.out.println("");
        System.out.println("Example");
        System.out.println("");
        System.out.println("// Student data");
        System.out.println("");
        System.out.println("String studentName = \"John Doe\";");
        System.out.println("int studentID = 15;");
        System.out.println("int studentAge = 23;");
        System.out.println("float studentFee = 75.25f;");
        System.out.println("char studentGrade = 'B';");
        System.out.println("");
        System.out.println("// Print variables");
        System.out.println("System.out.println(\"Student name: \" + studentName);");
        System.out.println("System.out.println(\"Student id: \" + studentID);");
        System.out.println("System.out.println(\"Student age: \" + studentAge);");
        System.out.println("System.out.println(\"Student fee: \" + studentFee);");
        System.out.println("System.out.println(\"Student grade: \" + studentGrade);");
        System.out.println("");
        System.out.println("");
      
    }
    
}
